### ISSUE TITLE
Delta Patcher Error

### ISSUE THREAD

**Issue by Fechulo** [judemille/GrayEuroScope#2]
```
[12:53:14] Original file "EuroScope.exe" selected.
[12:53:21] Patch file "ESDarkGray.xdelta" selected.
[12:53:24] Applying patch, please wait... (don't panic!)
[12:53:24] An error has occurred: xdelta3: source file too short: XD3_INVALID_INPUT
```

Running on Windows 10

**Comment by judemille** [comment]
To confirm, are you performing this with a clean EuroScope exe (either from backup, or from running the installer in repair mode)?

**Comment by Fechulo** [comment]
Yep, ran the installer repair and tried again, same thing

**Comment by judemille** [comment]
I've pushed a new xdelta patch -- not sure what changed, but maybe this will work better. Perhaps I made the last version I pushed wrong.

**Comment by Fechulo** [comment]
That worked! Had some errors due to permissions, but running DeltaPatcher as administrator fixed those

Awesome job btw 🔥 I'd been trying to do something similar for some time but couldn't quite crack it

**Comment by judemille** [comment]
Yeah, this one had me scratching my head for a few hours, but luckily I've gotten some experience with Ghidra lately, so I managed to work it out.
